name: Auto-Merge Jules PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'google-labs-jules[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Approve and Merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr ready "$PR_URL" || true
          gh pr review "$PR_URL" --approve --body "Auto-approved."
          gh pr merge "$PR_URL" --auto --squash
